### ISSUE TITLE
emoji (unicode char) into the html of the page make lxml return empty body

### ISSUE THREAD

**Issue by clawfire** [Donohue/medium-to-jekyll#3]
my posts with emoji char (unicode) in it are making `lxml.html.document_fromstring(html)` return `<html><body><p>!   D   O   C   T   Y   P   E       h   t   m   l   &gt;   </p></body></html>` instead of the proper html code.

Which then cause an error while parsing the HTML later : 
```
Traceback (most recent call last):
  File "medium_to_jekyll.py", line 110, in <module>
    main()
  File "medium_to_jekyll.py", line 100, in main
    title, date = extract_metadata(doc)
  File "medium_to_jekyll.py", line 34, in extract_metadata
    title = etree.tostring(doc.xpath('//title')[0], method='text', encoding='unicode')
IndexError: list index out of range

```
While I'm looking for the `document_fromstring()` on the lxml doc I noticed this : 

> Really broken pages
> The normal HTML parser is capable of handling broken HTML, but for pages that are far enough from HTML to call them 'tag soup', it may still fail to parse the page in a useful way. A way to deal with this is ElementSoup, which deploys the well-known BeautifulSoup parser to build an lxml HTML tree.
> 
> However, note that the most common problem with web pages is the lack of (or the existence of incorrect) encoding declarations. It is therefore often sufficient to only use the encoding detection of BeautifulSoup, called UnicodeDammit, and to leave the rest to lxml's own HTML parser, which is several times faster.

I think there's something to investigate on this side

I'm using Python 3 ;)

**Comment by clawfire** [comment]
I tried replace `lxml.html.document_fromstring(html)` by `lxml.html.soupparser.fromstring(html)` while doing the proper import and it works like a charm. 

I will do a PR. The thing is, `soupparser` is a little bit slower than the regular `lxml` parser. It's not noticeable in our case here but it would be better to use a try statement. However, `lxml` return an incorrect HTML document **without** throwing error.

**Comment by dacapoday** [comment]
root cause and still not fix: https://bugs.launchpad.net/lxml/+bug/1949271

**Comment by Donohue** [comment]
Can you provide a file that is failing so I can test? Alternatively you can use the suggestion from @clawfire https://github.com/Donohue/medium-to-jekyll/pull/4

**Comment by dacapoday** [comment]
When I use Mac OS built-in python 3.8 to parse https://unicode.org/emoji/charts/full-emoji-list.html
trigger this problem.
